import { 
    async_post,
} from "./stores"

export const DATAPOINTS_PROPERTIES = {
    bool:       { type: 'bool',  text_false: 'OFF', text_true: 'ON' },
    int:        { type: 'int',   min: 0, max: 100, step: 1, units: "" },
    float:      { type: 'float', min: 0, max: 100, decimals: 2, step: 0.1, units: "" },
    str:        { type: 'str',   length: 18 },
}

export const DATA_TYPES = [
    { "name": "Boolean",     "value": "bool"   },
    { "name": "Integer",     "value": "int"    },
    { "name": "Float"  ,     "value": "float"  },
    { "name": "String" ,     "value": "str"    },
]

export const READ_WRITE = [
    { "name": "Read Only",   "value": false   },
    { "name": "Writable",    "value": true    },

] 

export const USER_PROFILES = [
    { "name": "Developer",     "value": "developer"   },
    { "name": "User",          "value": "user"  },
    { "name": "View Only",     "value": "view"  },
]


export async function build_app(application_name: string) {
    return await async_post( '/app_ide', 'build_app', {name: application_name} )     
}

export async function run_app(application_name: string) {
    return await async_post( '/app_ide', 'run_app', {name: application_name} )   
}

export async function stop_app(application_name: string) {
    return await async_post( '/app_ide', 'stop_app', {name: application_name} )   
}


export const UNITS_LIST = [
    { bac: 0,  value: 'm²',         name: 'square metre ' },
    { bac: 1,  value: 'ft²',        name: 'square foot ' },
    { bac: 2,  value: 'mA',         name: 'milliampere ' },
    { bac: 3,  value: 'A',          name: 'ampere ' },
    { bac: 4,  value: 'Ω',          name: 'ohm ' },
    { bac: 5,  value: 'V',          name: 'volt ' },
    { bac: 6,  value: 'kV',         name: 'kilovolt ' },
    { bac: 7,  value: 'MV',         name: 'megavolt ' },
    { bac: 8,  value: 'V·A',        name: 'volt - ampere ' },
    { bac: 9,  value: 'kV·A',       name: 'kilovolt - ampere ' },
    { bac: 10, value: 'MV·A',       name: 'megavolt - ampere ' },
    { bac: 11, value: '',           name: 'volt-amperes-reactive ' },
    { bac: 12, value: 'kvar',       name: 'kilovolt ampere (reactive) ' },
    { bac: 13, value: '',           name: 'megavolt-amperes-reactive ' },
    { bac: 14, value: '',           name: 'degrees-phase ' },
    { bac: 15, value: '',           name: 'power-factor ' },
    { bac: 16, value: 'J',          name: 'joule ' },
    { bac: 17, value: 'kJ',         name: 'kilojoule ' },
    { bac: 18, value: 'W·h',        name: 'watt hour ' },
    { bac: 19, value: 'kW·h',       name: 'kilowatt hour ' },
    { bac: 20, value: 'Btu',        name: 'British thermal unit (mean) ' },
    { bac: 21, value: 'thm (US)',   name: 'therm (U.S.) ' },
    { bac: 22, value: 'ton (US)/h', name: 'ton (US) per hour ' },
    { bac: 23, value: '',           name: 'joules-per-kilogram-dry-air ' },
    { bac: 24, value: '',           name: 'btus-per-pound-dry-air ' },
    { bac: 25, value: '',           name: 'cycles-per-hour ' },
    { bac: 26, value: '',           name: 'cycles-per-minute ' },
    { bac: 27, value: 'Hz',         name: 'hertz ' },
    { bac: 28, value: '',           name: 'grams-of-water-per-kilogram-dry-air ' },
    { bac: 29, value: '%RH',        name: 'percent-relative-humidity ' },
    { bac: 30, value: 'mm',         name: 'millimetre ' },
    { bac: 31, value: 'm',          name: 'metre ' },
    { bac: 32, value: 'in',         name: 'inch ' },
    { bac: 33, value: 'ft',         name: 'foot ' },
    { bac: 34, value: '',           name: 'watts-per-square-foot ' },
    { bac: 35, value: '',           name: 'watts-per-square-meter ' },
    { bac: 36, value: 'lm',         name: 'lumen ' },
    { bac: 37, value: 'lx',         name: 'lux ' },
    { bac: 38, value: 'ftc',        name: 'footcandle ' },
    { bac: 39, value: 'kg',         name: 'kilogram ' },
    { bac: 40, value: '',           name: 'pounds-mass ' },
    { bac: 41, value: '',           name: 'tons ' },
    { bac: 42, value: 'kg/s',       name: 'kilogram per second ' },
    { bac: 43, value: 'kg/min',     name: 'kilogram per minute ' },
    { bac: 44, value: 'kg/h',       name: 'kilogram per hour ' },
    { bac: 45, value: '',           name: 'pounds-mass-per-minute ' },
    { bac: 46, value: '',           name: 'pounds-mass-per-hour ' },
    { bac: 47, value: 'W ',         name: 'watt ' },
    { bac: 48, value: 'kW ',        name: 'kilowatt ' },
    { bac: 49, value: 'MW ',        name: 'megawatt ' },
    { bac: 50, value: 'Btuth/h ',   name: 'British thermal unit (thermochemical) per hour ' },
    { bac: 51, value: '',           name: 'horsepower ' },
    { bac: 52, value: '',           name: 'tons-refrigeration ' },
    { bac: 53, value: 'Pa',         name: 'pascal ' },
    { bac: 54, value: 'kPa',        name: 'kilopascal ' },
    { bac: 55, value: 'bar',        name: 'bar [unit of pressure] ' },
    { bac: 56, value: 'lbf/in²',    name: 'pound-force per square inch ' },
    { bac: 57, value: '',           name: 'centimeters-of-water ' },
    { bac: 58, value: 'inH2O',      name: 'inch of water ' },
    { bac: 59, value: '',           name: 'millimeters-of-mercury ' },
    { bac: 60, value: 'cm Hg',      name: 'centimetre of mercury ' },
    { bac: 61, value: 'inHg',       name: 'inch of mercury ' },
    { bac: 62, value: '°C',         name: 'degree Celsius ' },
    { bac: 63, value: 'K',          name: 'kelvin ' },
    { bac: 64, value: '°F',         name: 'degree Fahrenheit ' },
    { bac: 65, value: '',           name: 'degree-days-Celsius ' },
    { bac: 66, value: '',           name: 'degree-days-Fahrenheit ' },
    { bac: 67, value: '',           name: 'years ' },
    { bac: 68, value: 'mo',         name: 'month ' },
    { bac: 69, value: 'wk',         name: 'week ' },
    { bac: 70, value: 'd',          name: 'day ' },
    { bac: 71, value: 'h',          name: 'hour ' },
    { bac: 72, value: 'min',        name: 'minute [unit of time] ' },
    { bac: 73, value: 's',          name: 'second [unit of time] ' },
    { bac: 74, value: 'm/s',        name: 'metre per second ' },
    { bac: 75, value: 'km/h',       name: 'kilometre per hour ' },
    { bac: 76, value: 'ft/s',       name: 'foot per second ' },
    { bac: 77, value: 'ft/min',     name: 'foot per minute ' },
    { bac: 78, value: 'mile/h',     name: 'mile per hour (statute mile) ' },
    { bac: 79, value: 'ft³',        name: 'cubic foot ' },
    { bac: 80, value: 'm³',         name: 'cubic metre ' },
    { bac: 81, value: '',           name: 'imperial-gallons ' },
    { bac: 82, value: 'l',          name: 'litre ' },
    { bac: 83, value: 'gal (US)',   name: 'gallon (US) ' },
    { bac: 84, value: 'ft³/min',    name: 'cubic foot per minute ' },
    { bac: 85, value: 'm³/s',       name: 'cubic metre per second ' },
    { bac: 86, value: 'gal (UK) /min', name: 'Imperial gallon per minute ' },
    { bac: 87, value: 'l/s',        name: 'litre per second ' },
    { bac: 88, value: 'l/min',      name: 'litre per minute ' },
    { bac: 89, value: 'gal (US) /min', name: 'US gallon per minute ' },
    { bac: 90, value: '°',          name: 'degree [unit of angle] ' },
    { bac: 91, value: '°C/h',       name: 'degree Celsius per hour ' },
    { bac: 92, value: '°C/min',     name: 'degree Celsius per minute ' },
    { bac: 93, value: '°F/h',       name: 'degree Fahrenheit per hour ' },
    { bac: 94, value: '°F/min',     name: 'degree Fahrenheit per minute ' },
    { bac: 95, value: '',           name: 'no-units ' },
    { bac: 96, value: '',           name: 'parts-per-million ' },
    { bac: 97, value: '',           name: 'parts-per-billion ' },
    { bac: 98, value: '%',          name: 'percent ' },
    { bac: 99, value: '',           name: 'percent-per-second ' },
    { bac: 100, value: '',          name: 'per-minute ' },
    { bac: 101, value: '',          name: 'per-second ' },
    { bac: 102, value: '',          name: 'psi-per-degree-Fahrenheit ' },
    { bac: 103, value: '',          name: 'radians ' },
    { bac: 104, value: 'r/min',     name: 'revolutions per minute ' },
    { bac: 105, value: '',          name: 'currency1 ' },
    { bac: 106, value: '',          name: 'currency2 ' },
    { bac: 107, value: '',          name: 'currency3 ' },
    { bac: 108, value: '',          name: 'currency4 ' },
    { bac: 109, value: '',          name: 'currency5 ' },
    { bac: 110, value: '',          name: 'currency6 ' },
    { bac: 111, value: '',          name: 'currency7 ' },
    { bac: 112, value: '',          name: 'currency8 ' },
    { bac: 113, value: '',          name: 'currency9 ' },
    { bac: 114, value: '',          name: 'currency10 ' },
    { bac: 115, value: 'in²',       name: 'square inch ' },
    { bac: 116, value: 'cm²',       name: 'square centimetre ' },
    { bac: 117, value: 'BtuIT/lb',  name: 'British thermal unit (international table) per pound ' },
    { bac: 118, value: 'cm',        name: 'centimetre ' },
    { bac: 119, value: '',          name: 'pounds-mass-per-second ' },
    { bac: 120, value: '',          name: 'delta-degrees-Fahrenheit ' },
    { bac: 121, value: '',          name: 'delta-degrees-Kelvin ' },
    { bac: 122, value: 'kΩ',        name: 'kiloohm ' },
    { bac: 123, value: 'MΩ',        name: 'megaohm ' },
    { bac: 124, value: 'mV',        name: 'millivolt ' },
    { bac: 125, value: 'kJ/kg',     name: 'kilojoule per kilogram ' },
    { bac: 126, value: 'MJ',        name: 'megajoule ' },
    { bac: 127, value: '',          name: 'joules-per-degree-Kelvin ' },
    { bac: 128, value: '',          name: 'joules-per-kilogram-degree-Kelvin ' },
    { bac: 129, value: 'kHz',       name: 'kilohertz ' },
    { bac: 130, value: 'MHz',       name: 'megahertz ' },
    { bac: 131, value: '',          name: 'per-hour ' },
    { bac: 132, value: 'mW',        name: 'milliwatt ' },
    { bac: 133, value: 'hPa',       name: 'hectopascal ' },
    { bac: 134, value: 'mbar',      name: 'millibar ' },
    { bac: 135, value: 'm³/h',      name: 'cubic metre per hour ' },
    { bac: 136, value: '',          name: 'liters-per-hour ' },
    { bac: 137, value: '',          name: 'kilowatt-hours-per-square-meter ' },
    { bac: 138, value: '',          name: 'kilowatt-hours-per-square-foot ' },
    { bac: 139, value: '',          name: 'megajoules-per-square-meter ' },
    { bac: 140, value: '',          name: 'megajoules-per-square-foot ' },
    { bac: 141, value: '',          name: 'watts-per-square-meter-degree-kelvin ' },
    { bac: 142, value: '',          name: 'cubic-feet-per-second ' },
    { bac: 143, value: '',          name: 'percent-obscuration-per-foot ' },
    { bac: 144, value: '',          name: 'percent-obscuration-per-meter ' },
    { bac: 145, value: 'mΩ',        name: 'milliohm ' },
    { bac: 146, value: 'MW·h',      name: 'megawatt hour (1000 kW.h) ' },
    { bac: 147, value: '',          name: 'kilo-btus ' },
    { bac: 148, value: '',          name: 'mega-btus ' },
    { bac: 149, value: '',          name: 'kilojoules-per-kilogram-dry-air ' },
    { bac: 150, value: '',          name: 'megajoules-per-kilogram-dry-air ' },
    { bac: 151, value: '',          name: 'kilojoules-per-degree-Kelvin ' },
    { bac: 152, value: '',          name: 'megajoules-per-degree-Kelvin ' },
    { bac: 153, value: 'N',         name: 'newton ' },
    { bac: 154, value: 'g/s',       name: 'gram per second ' },
    { bac: 155, value: 'g/min',     name: 'gram per minute ' },
    { bac: 156, value: 't/h',       name: 'tonne per hour ' },
    { bac: 157, value: '',          name: 'kilo-btus-per-hour ' },
    { bac: 158, value: '',          name: 'hundredths-seconds ' },
    { bac: 159, value: 'ms',        name: 'millisecond ' },
    { bac: 160, value: 'N·m',       name: 'newton metre ' },
    { bac: 161, value: 'mm/s',      name: 'millimetre per second ' },
    { bac: 162, value: 'mm/min',    name: 'millimetre per minute ' },
    { bac: 163, value: 'm/min',     name: 'metre per minute ' },
    { bac: 164, value: 'm/h',       name: 'metre per hour ' },
    { bac: 165, value: 'm³/min',    name: 'cubic metre per minute ' },
    { bac: 166, value: 'm/s²',      name: 'metre per second squared ' },
    { bac: 167, value: 'A/m',       name: 'ampere per metre ' },
    { bac: 168, value: 'A/m²',      name: 'ampere per square metre ' },
    { bac: 169, value: 'A·m²',      name: 'ampere square metre ' },
    { bac: 170, value: 'F',         name: 'farad ' },
    { bac: 171, value: 'H',         name: 'henry ' },
    { bac: 172, value: 'Ω·m',       name: 'ohm metre ' },
    { bac: 173, value: 'S',         name: 'siemens ' },
    { bac: 174, value: 'S/m',       name: 'siemens per metre ' },
    { bac: 175, value: 'T',         name: 'tesla ' },
    { bac: 176, value: 'V/K',       name: 'volt per kelvin ' },
    { bac: 177, value: 'V/m',       name: 'volt per metre ' },
    { bac: 178, value: 'Wb',        name: 'weber ' },
    { bac: 179, value: 'cd',        name: 'candela ' },
    { bac: 180, value: 'cd/m²',     name: 'candela per square metre ' },
    { bac: 181, value: 'K/h',       name: 'kelvin per hour ' },
    { bac: 182, value: 'K/min',     name: 'kelvin per minute ' },
    { bac: 183, value: 'J·s',       name: 'joule second ' },
    { bac: 184, value: 'rad/s',     name: 'radian per second ' },
    { bac: 185, value: 'm²/N',      name: 'square metre per newton ' },
    { bac: 186, value: 'kg/m³',     name: 'kilogram per cubic metre ' },
    { bac: 187, value: 'N·s',       name: 'newton second ' },
    { bac: 188, value: 'N/m',       name: 'newton per metre ' },
    { bac: 189, value: 'W/(m·K)',   name: 'watt per metre kelvin ' },
    { bac: 190, value: 'µS',        name: 'microsiemens ' },
    { bac: 191, value: 'ft³/h',     name: 'cubic foot per hour ' },
    { bac: 192, value: '',          name: 'us-gallons-per-hour ' },
    { bac: 193, value: 'km',        name: 'kilometre ' },
    { bac: 194, value: 'µm',        name: 'micrometre (micron) ' },
    { bac: 195, value: 'g',         name: 'gram ' },
    { bac: 196, value: 'mg',        name: 'milligram ' },
    { bac: 197, value: 'ml',        name: 'millilitre ' },
    { bac: 198, value: 'ml/s',      name: 'millilitre per second ' },
    { bac: 199, value: 'dB',        name: 'decibel ' },
    { bac: 200, value: '',          name: 'decibels-millivolt ' },
    { bac: 201, value: '',          name: 'decibels-volt ' },
    { bac: 202, value: 'mS',        name: 'millisiemens ' },
    { bac: 203, value: '',          name: 'watt-hours-reactive ' },
    { bac: 204, value: '',          name: 'kilowatt-hours-reactive ' },
    { bac: 205, value: '',          name: 'megawatt-hours-reactive ' },
    { bac: 206, value: '',          name: 'millimeters-of-water ' },
    { bac: 207, value: '',          name: 'per-mille ' },
    { bac: 208, value: '',          name: 'grams-per-gram ' },
    { bac: 209, value: 'kg/kg',     name: 'kilogram per kilogram ' },
    { bac: 210, value: '',          name: 'grams-per-kilogram ' },
    { bac: 211, value: 'mg/g',      name: 'milligram per gram ' },
    { bac: 212, value: 'mg/kg',     name: 'milligram per kilogram ' },
    { bac: 213, value: 'g/ml',      name: 'gram per millilitre ' },
    { bac: 214, value: 'g/l',       name: 'gram per litre ' },
    { bac: 215, value: 'mg/l',      name: 'milligram per litre ' },
    { bac: 216, value: 'µg/l',      name: 'microgram per litre ' },
    { bac: 217, value: 'g/m³',      name: 'gram per cubic metre ' },
    { bac: 218, value: 'mg/m³',     name: 'milligram per cubic metre ' },
    { bac: 219, value: 'µg/m³',     name: 'microgram per cubic metre ' },
    { bac: 220, value: '',          name: 'nanograms-per-cubic-meter ' },
    { bac: 221, value: 'g/cm³',     name: 'gram per cubic centimetre ' },
    { bac: 222, value: 'Bq',        name: 'becquerel ' },
    { bac: 223, value: 'kBq',       name: 'kilobecquerel ' },
    { bac: 224, value: 'MBq',       name: 'megabecquerel ' },
    { bac: 225, value: 'Gy',        name: 'gray ' },
    { bac: 226, value: 'mGy',       name: 'milligray ' },
    { bac: 227, value: '',          name: 'microgray ' },
    { bac: 228, value: 'Sv',        name: 'sievert ' },
    { bac: 229, value: 'mSv',       name: 'millisievert ' },
    { bac: 230, value: '',          name: 'microsieverts ' },
    { bac: 231, value: 'µSv/h',     name: 'microsievert per hour ' },
    { bac: 232, value: '',          name: 'decibels-a ' },
    { bac: 233, value: '',          name: 'nephelometric-turbidity-unit ' },
    { bac: 234, value: 'pH',        name: 'pH (potential of Hydrogen) ' },
    { bac: 235, value: 'g/m²',      name: 'gram per square metre ' },
    { bac: 236, value: '',          name: 'minutes-per-degree-kelvin ' },
]